# Assignment 2 – Python with Data Analytics 

1. Explain the difference between a Python list and a NumPy array in terms of 
memory usage and performance. 
Then, write a program that creates both and performs element-wise 
multiplication. 

 Answer1.
 Python List-
* Elements are stored as object references, not raw values.
* Can store mixed data types so require more memory usage.
* Slower in performance. 
* Element-wise operations require explicit loops, which makes them slower.

NumPy Array-
* Elements are stored in contiguous memory blocks.
* All elements are of the same data type so memory is used efficiently.
* Uses vectorized operations implemented in C.
* Much faster for numerical and mathematical computations.

In [1]:
# Python Lists
list1 = [1, 2, 3, 4]
list2 = [5, 6, 7, 8]
list_result = []
for i in range(len(list1)):
    list_result.append(list1[i] * list2[i])
print("multiplicated list:", list_result)

multiplicated list: [5, 12, 21, 32]


In [2]:
import numpy as np

In [4]:
# NumPy Array
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])
array_result = array1 * array2
print("multiplicated array:", array_result)

multiplicated array: [ 5 12 21 32]


2. What is broadcasting in NumPy? 
Create a 3×3 NumPy array and add a 1D array to it using broadcasting. Explain how NumPy applies the operation internally.  

Answer2.
 Broadcasting allows NumPy to perform arithmetic operations on arrays of different shapes by automatically expanding the smaller array.

In [5]:
matrix = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
array = np.array([10, 20, 30])
result = matrix + array
print(result)


[[11 22 33]
 [14 25 36]
 [17 28 39]]


* explanation-
* matrix is of size (3X3) and array is of (3X1)
* In general multiplaction is done two matrices can be added only if they have the same dimensions
* In numpy 
1d array is automatically converted into 3X3 matrix to perform addition
* so 1d array become [[10, 20, 30],[10, 20, 30],[10, 20, 30]]



3. What are missing values in Pandas and how are they represented? 
Create a DataFrame with missing values and write code to: 
* Detect missing values 
* Replace them with the column mean 
Explain each step.

Answer3.

Missing values represent unavailable or undefined data.
Representations-
* NaN (Not a Number)
* None

In [10]:
import pandas as pd
import numpy as np
data = {
    "Maths": [80, 90, np.nan, 70],
    "Science": [85, np.nan, 75, 95],
    "English": [np.nan, 88, 92, 85]
}
df = pd.DataFrame(data)
print(df)

   Maths  Science  English
0   80.0     85.0      NaN
1   90.0      NaN     88.0
2    NaN     75.0     92.0
3   70.0     95.0     85.0


In [11]:
print(df.isnull()) #checking null values


   Maths  Science  English
0  False    False     True
1  False     True    False
2   True    False    False
3  False    False    False


In [14]:
ndf = df.fillna(df.mean())  #replacing null values with mean col value
print(ndf)


   Maths  Science    English
0   80.0     85.0  88.333333
1   90.0     85.0  88.000000
2   80.0     75.0  92.000000
3   70.0     95.0  85.000000


4. Explain boolean indexing in NumPy or Pandas. 
Create a DataFrame with at least 5 columns and filter rows based on two conditions 
using logical operators. Explain how filtering works internally.

Answer4. Boolean Indexing

It filters data using True/False conditions.

In [6]:
import pandas as pd

In [8]:
data = {
    "Name": ["A", "B", "C", "D", "E"],
    "Age": [20, 22, 19, 24, 21],
    "Marks": [85, 78, 90, 65, 88],
    "Gender": ["F", "M", "M", "F", "F"],
    "Pass": [True, True, True, False, True]
}
df = pd.DataFrame(data)
filter= df[(df["Age"] > 20) & (df["Marks"] > 80)]
print(filter)

  Name  Age  Marks Gender  Pass
4    E   21     88      F  True


5. What is the purpose of the groupby() function in Pandas? 
Create a DataFrame with categorical data (e.g., department & salary) and calculate 
the average salary per department using groupby(). Explain the output.

Answer5. 
groupby() is used to:

* Split data into groups
* Apply aggregation functions
* Then combine results


In [9]:
data = {
    "Department": ["HR", "IT", "HR", "IT", "Finance", "Finance"],
    "Salary": [30000, 50000, 35000, 55000, 40000, 42000]
}
df = pd.DataFrame(data)
avg_salary = df.groupby("Department")["Salary"].mean()
print(avg_salary)

Department
Finance    41000.0
HR         32500.0
IT         52500.0
Name: Salary, dtype: float64


* Explanation

Data is grouped by department then Mean salary calculated for each group